/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthyme;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Parth Anil Bidave S
 */
public class Createprofile extends javax.swing.JFrame {

    /**
     * Creates new form Createprofile
     */ 
    public Createprofile() {
        initComponents();
        setLocation(250,70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        calorie = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        cnfpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sora", 1, 36)); // NOI18N
        jLabel2.setText("CREATE YOUR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 300, 70));

        jLabel3.setFont(new java.awt.Font("Sora", 1, 14)); // NOI18N
        jLabel3.setText("healthyme...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 100, 30));

        jLabel4.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel4.setText("Height");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 80, -1));

        jLabel5.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 60, -1));

        jLabel6.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel6.setText("Calorie Goal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 120, -1));

        jLabel7.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 60, -1));

        jLabel9.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 80, -1));

        jLabel10.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel10.setText("Weight");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 90, -1));

        gender.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 170, 30));

        name.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 170, 30));

        age.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 170, 30));

        weight.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 170, 30));

        calorie.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(calorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 170, 30));

        height.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 170, 30));

        btnsubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnsubmit.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 210, 40));

        jLabel8.setFont(new java.awt.Font("Sora", 1, 48)); // NOI18N
        jLabel8.setText("PROFILE.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 280, 70));

        jLabel11.setFont(new java.awt.Font("Sora", 0, 12)); // NOI18N
        jLabel11.setText("Note : Please enter your weight in kilograms and height in meters");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, -1));

        jLabel13.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 100, -1));

        jLabel14.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        jLabel14.setText("Cnf Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, -1));

        email.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, 30));

        pass.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 170, 30));

        cnfpass.setBackground(new java.awt.Color(210, 238, 219));
        jPanel1.add(cnfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healthyme/main fade.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healtyme","root","root");
String sql = "INSERT INTO profile(email, password, cnfpass, name, age, gender, weight, height, calorie)values(?,?,?,?,?,?,?,?,?)";
PreparedStatement pst = conn.prepareStatement(sql);

// Set values into the prepared statement
pst.setString(1, email.getText());
pst.setString(2, pass.getText());
pst.setString(3, cnfpass.getText());
pst.setString(4, name.getText());
pst.setInt(5,Integer.parseInt(age.getText()));
pst.setString(6, gender.getText());
pst.setDouble(7, Double.parseDouble(weight.getText()));
pst.setDouble(8, Double.parseDouble(height.getText()));
pst.setInt(9, Integer.parseInt(calorie.getText()));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            conn.close();
            LOGIN1 obj = new LOGIN1();
            obj.show();
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Createprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Createprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Createprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Createprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Createprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JTextField calorie;
    private javax.swing.JTextField cnfpass;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
