/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthyme;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Parth Anil Bidave S
 */
public class LOGIN1 extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN1
     */
    private profile pg;
  
    public LOGIN1() {
        initComponents();
        setLocation(250,70);
        pg=new profile();
        
        
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtemail = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        edtpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sora", 1, 36)); // NOI18N
        jLabel2.setText("healthyme...");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 250, -1));

        jLabel4.setFont(new java.awt.Font("Sora", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 92, -1));

        jLabel5.setFont(new java.awt.Font("Sora", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 92, -1));

        edtemail.setBackground(new java.awt.Color(214, 250, 214));
        edtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtemailActionPerformed(evt);
            }
        });
        jPanel1.add(edtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 239, 32));

        btnsubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnsubmit.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 340, 240, -1));

        jLabel6.setFont(new java.awt.Font("Sora", 0, 24)); // NOI18N
        jLabel6.setText("SIGN IN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, 59));

        edtpass.setBackground(new java.awt.Color(214, 250, 214));
        jPanel1.add(edtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
                                         
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

try {
    // Establish connection to the database
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/healtyme", "root", "root");

    // Validate login
    String sql = "SELECT * FROM profile WHERE email=? AND cnfpass=?";
    pst = conn.prepareStatement(sql);
    pst.setString(1, edtemail.getText()); // Email from input field
    pst.setString(2, String.valueOf(edtpass.getPassword())); // Secure password handling
    
    rs = pst.executeQuery();
    
    if (rs.next()) {
        // Query to fetch profile data
        String sql1 = "SELECT name, age, weight, height, gender, calorie FROM profile WHERE email=?";
        pst = conn.prepareStatement(sql1);
        pst.setString(1, edtemail.getText());
        ResultSet rs1 = pst.executeQuery();
        
        if (rs1.next()) {
            // Retrieve and set profile data to the UI components
           String name = rs.getString("name");
           pg.setTextName("Name: " + name);

           String age = rs1.getString("age");
           pg.setTextAge("Age: " + age);
           
           String weight = rs1.getString("weight");
           pg.setTextWeight("Weight: " + weight);
           
           String height = rs1.getString("height");
           pg.setTextHeight("Height: " + height);
           
           String gender = rs1.getString("gender");
           pg.setTextGender("Gender: " + gender);
           
           String calorie = rs1.getString("calorie");
           pg.setTextCalorie("Calorie: " + calorie);

            
            // Open the profile window and close the login window
            pg.setVisible(true);
            dispose(); // Close the login window
        } 
    }
} catch(Exception e) {
    // Handle exceptions and show a message dialog with the error
    JOptionPane.showMessageDialog(null, e);
} finally {
    try {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
        if (conn != null) conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    }//GEN-LAST:event_btnsubmitActionPerformed

    private void edtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JTextField edtemail;
    private javax.swing.JPasswordField edtpass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
